import type { BodyType } from '../../lib/axios';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * SAGEP Core API
 * OpenAPI spec version: 1.0
 */
import type {
  LoginDto,
  ReadUsuarioDto,
  LoginResponseDto,
  PaginateRolesDto,
  AuthControllerPaginateRolesParams,
} from '../generated.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAutenticação = () => {
  /**
   * @summary Autenticar usuário
   */
  const login = (
    loginDto: BodyType<LoginDto>,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<LoginResponseDto>(
      {
        url: `/auth/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: loginDto,
      },
      options
    );
  /**
   * @summary Obter perfil do usuário autenticado
   */
  const me = (options?: SecondParameter<typeof customInstance>) => customInstance<ReadUsuarioDto>({ url: `/auth/me`, method: 'GET' }, options);
  /**
   * @summary Obter todos os papéis
   */
  const paginateRoles = (
    params?: AuthControllerPaginateRolesParams,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<PaginateRolesDto>({ url: `/auth/roles`, method: 'GET', params }, options);
  return { login, me, paginateRoles };
};
export type LoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAutenticação>['login']>>
>;
export type MeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticação>['me']>>>;
export type PaginateRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAutenticação>['paginateRoles']>>
>;
