import type { BodyType } from '../../lib/axios';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * SAGEP Core API
 * OpenAPI spec version: 1.0
 */
import type { RoleDto, PaginateDto, PermissionDto } from '../permissions/permissions';
import type {
  LoginDto,
  ReadUsuarioDto,
  LoginResponseDto,
  AuthControllerPaginateRolesParams,
} from '../generated.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAutenticação = () => {
  /**
   * @summary Autenticar usuário
   */
  const login = (loginDto: BodyType<LoginDto>, options?: SecondParameter<typeof customInstance>) =>
    customInstance<LoginResponseDto>(
      {
        url: `/auth/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: loginDto,
      },
      options
    );
  /**
   * @summary Obter perfil do usuário autenticado
   */
  const me = (options?: SecondParameter<typeof customInstance>) =>
    customInstance<ReadUsuarioDto>({ url: `/auth/me`, method: 'GET' }, options);
  /**
   * @summary Obter todos os papéis
   */
  const paginateRoles = (
    params?: AuthControllerPaginateRolesParams,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<PaginateDto<RoleDto>>({ url: `/auth/roles`, method: 'GET', params }, options);

  const listPermissions = (options?: SecondParameter<typeof customInstance>) =>
    customInstance<PermissionDto[]>({ url: `/auth/permissions`, method: 'GET' }, options);

  const createRole = (
    dto: BodyType<{ nome: string; descricao: string; permissionIds?: string[] }>,
    options?: SecondParameter<typeof customInstance>
  ) =>
    customInstance<RoleDto>(
      {
        url: `/auth/roles`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: dto,
      },
      options
    );
  const updateRole = (
    id: string,
    dto: BodyType<{ nome?: string; descricao?: string; permissionIds?: string[] }>,
    options?: SecondParameter<typeof customInstance>
  ) =>
    customInstance<RoleDto>(
      {
        url: `/auth/roles/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: dto,
      },
      options
    );
  const removeRole = (id: string, options?: SecondParameter<typeof customInstance>) =>
    customInstance<void>({ url: `/auth/roles/${id}`, method: 'DELETE' }, options);

  return { login, me, paginateRoles, listPermissions, createRole, updateRole, removeRole };
};
export type LoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAutenticação>['login']>>
>;
export type MeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticação>['me']>>>;
export type PaginateRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAutenticação>['paginateRoles']>>
>;
