import type { BodyType } from '../../lib/axios';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * SAGEP Core API
 * OpenAPI spec version: 1.0
 */
import type {
  ReadUnidadePrisionalDto,
  CreateUnidadePrisionalDto,
  UpdateUnidadePrisionalDto,
  PaginateUnidadePrisionalDto,
  UnidadePrisionalControllerFindAllParams,
} from '../generated.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUnidadesPrisionais = () => {
  /**
   * @summary Criar uma nova unidade prisional
   */
  const create = (
    createUnidadePrisionalDto: BodyType<CreateUnidadePrisionalDto>,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<ReadUnidadePrisionalDto>(
      {
        url: `/unidades-prisionais`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createUnidadePrisionalDto,
      },
      options
    );
  /**
   * @summary Listar todas as unidades prisionais
   */
  const findAll = (
    params?: UnidadePrisionalControllerFindAllParams,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<PaginateUnidadePrisionalDto>(
      { url: `/unidades-prisionais`, method: 'GET', params },
      options
    );
  /**
   * @summary Buscar uma unidade prisional pelo ID
   */
  const findOne = (id: string, options?: SecondParameter<typeof customInstance>) => customInstance<ReadUnidadePrisionalDto>(
      { url: `/unidades-prisionais/${id}`, method: 'GET' },
      options
    );
  /**
   * @summary Atualizar uma unidade prisional pelo ID
   */
  const update = (
    id: string,
    updateUnidadePrisionalDto: BodyType<UpdateUnidadePrisionalDto>,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<ReadUnidadePrisionalDto>(
      {
        url: `/unidades-prisionais/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateUnidadePrisionalDto,
      },
      options
    );
  /**
   * @summary Remover uma unidade prisional pelo ID
   */
  const remove = (id: string, options?: SecondParameter<typeof customInstance>) => customInstance<void>({ url: `/unidades-prisionais/${id}`, method: 'DELETE' }, options);
  return { create, findAll, findOne, update, remove };
};
export type CreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUnidadesPrisionais>['create']>>
>;
export type FindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUnidadesPrisionais>['findAll']>>
>;
export type FindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUnidadesPrisionais>['findOne']>>
>;
export type UpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUnidadesPrisionais>['update']>>
>;
export type RemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUnidadesPrisionais>['remove']>>
>;
