/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * SAGEP Core API
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck200 } from '../generated.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getHealth = () => {
  const check = (options?: SecondParameter<typeof customInstance>) => customInstance<HealthControllerCheck200>({ url: `/health`, method: 'GET' }, options);
  return { check };
};
export type CheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['check']>>>;
