import type { BodyType } from '../../lib/axios';
/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * SAGEP Core API
 * OpenAPI spec version: 1.0
 */
import type {
  ReadUsuarioDto,
  CreateUsuarioDto,
  UpdateUsuarioDto,
  PaginateUsuarioDto,
  UsuarioControllerPaginateParams,
} from '../generated.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUsuários = () => {
  /**
   * @summary Criar um novo usuário
   */
  const create = (
    createUsuarioDto: BodyType<CreateUsuarioDto>,
    options?: SecondParameter<typeof customInstance>
  ) =>
    customInstance<ReadUsuarioDto>(
      {
        url: `/usuarios`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createUsuarioDto,
      },
      options
    );
  /**
   * @summary Listar todos os usuários
   */
  const paginate = (
    params?: UsuarioControllerPaginateParams,
    options?: SecondParameter<typeof customInstance>
  ) => customInstance<PaginateUsuarioDto>({ url: `/usuarios`, method: 'GET', params }, options);
  /**
   * @summary Buscar um usuário pelo ID
   */
  const findOne = (id: string, options?: SecondParameter<typeof customInstance>) =>
    customInstance<ReadUsuarioDto>({ url: `/usuarios/${id}`, method: 'GET' }, options);
  /**
   * @summary Atualizar um usuário pelo ID
   */
  const update = (
    id: string,
    updateUsuarioDto: BodyType<UpdateUsuarioDto>,
    options?: SecondParameter<typeof customInstance>
  ) =>
    customInstance<ReadUsuarioDto>(
      {
        url: `/usuarios/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateUsuarioDto,
      },
      options
    );
  /**
   * @summary Remover um usuário pelo ID
   */
  const remove = (id: string, options?: SecondParameter<typeof customInstance>) =>
    customInstance<void>({ url: `/usuarios/${id}`, method: 'DELETE' }, options);
  return { create, paginate, findOne, update, remove };
};
export type CreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsuários>['create']>>
>;
export type PaginateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsuários>['paginate']>>
>;
export type FindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsuários>['findOne']>>
>;
export type UpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsuários>['update']>>
>;
export type RemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsuários>['remove']>>
>;
